### ISSUE TITLE
Leaderboard not working

### ISSUE THREAD

**Issue by arjun921** [sig-ml/crossval#3] opened 2016-10-14 11:21 UTC

**Comment by theSage21** [comment] 2016-10-15 03:46
I'm unable to reproduce the issue. Try seeing if this is happening on your end too. In fact, I think this was a one off on the college servers.

**Comment by arjun921** [comment] 2016-10-22 10:42
<img width="1680" alt="screen shot 2016-10-22 at 4 06 43 pm" src="https://cloud.githubusercontent.com/assets/10341039/19618793/e9dfb642-9871-11e6-843c-147a51c7ae07.png">
<img width="1677" alt="screen shot 2016-10-22 at 4 06 57 pm" src="https://cloud.githubusercontent.com/assets/10341039/19618796/ec6aebd4-9871-11e6-9807-57a672f0442e.png">
<img width="1676" alt="screen shot 2016-10-22 at 4 07 09 pm" src="https://cloud.githubusercontent.com/assets/10341039/19618797/ee00966a-9871-11e6-9d7f-ba557513dd6f.png">
<img width="1669" alt="screen shot 2016-10-22 at 4 07 31 pm" src="https://cloud.githubusercontent.com/assets/10341039/19618801/f94f027c-9871-11e6-84c8-b44b408d930b.png">
<img width="1677" alt="screen shot 2016-10-22 at 4 07 49 pm" src="https://cloud.githubusercontent.com/assets/10341039/19618802/02aae66a-9872-11e6-842e-38094a279981.png">
<img width="1672" alt="screen shot 2016-10-22 at 4 08 18 pm" src="https://cloud.githubusercontent.com/assets/10341039/19618803/04f0b9f4-9872-11e6-9f23-26a3affc1f34.png">
<img width="1669" alt="screen shot 2016-10-22 at 4 08 27 pm" src="https://cloud.githubusercontent.com/assets/10341039/19618804/06ea4400-9872-11e6-9d6b-1b2363144e04.png">

Wouldn't have been able to copy all the text with the correct headings and hierarchy so uploaded screenshots instead.

**Comment by theSage21** [comment] 2016-10-22 12:11
I'm still having trouble reproducing it. Exactly what conditions lead to this is what we need. Can you diagnose that?

**Comment by theSage21** [comment] 2016-10-25 20:59
Resolved in https://github.com/sig-ml/crossval/commit/788297df4d93c37d48ffba9d11b2e9a07522f409

**Closed as completed by theSage21** 2016-10-25 20:59 UTC
Labels: bug
